spring:
  application:
    name: gateway-service
  config:
    import: optional:configserver:http://localhost:8071
  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: false
              lower-case-service-id: true

info:
  app:
    name: gateway-service
    description: "Gateway Server Application"
    version: 1.0.0

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    gateway:
      access: unrestricted
  info:
    env:
      enabled: true

logging:
  level:
    com:
      dev:
        gateway_service: DEBUG



