spring:
  application:
    name: gateway-service
  config:
    import: optional:configserver:http://localhost:8071
  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: false
              lower-case-service-id: true
          httpclient:
            connect-timeout: 1000
            response-timeout: 100s
  data:
    redis:
      connect-timeout: 2s
      host: localhost
      port: 6379
      timeout: 1s
info:
  app:
    name: gateway-service
    description: "Gateway Server Application"
    version: 1.0.0

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    gateway:
      access: unrestricted
  info:
    env:
      enabled: true
  metrics:
    tags:
      application: ${spring.application.name}

logging:
  level:
    com:
      dev:
        gateway_service: DEBUG
  pattern:
    level: "%5p [${spring.application.name},%X{trace_id},%X{span_id}]"

resilience4j:
  circuitbreaker:
    configs:
      default:
        sliding-window-size: 30
        permitted-number-of-calls-in-half-open-state: 2
        failure-rate-threshold: 80
        wait-duration-in-open-state:
          seconds: 100



