spring:
  application:
    name: accounts
  datasource:
    url: jdbc:mysql://localhost:3306/accountdb
    username: root
    password: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update  # or create-drop for development
      database-platform: org.hibernate.dialect.MySQL8Dialect
  sql:
    init:
      mode: always
  profiles:
    active: default
  config:
    import: optional:configserver:http://localhost:8071
#  rabbitmq:
#    host: localhost
#    port: 5672
#    username: guest
#    password: guest

server:
  port: 9090

management:
  endpoints:
    web:
      exposure:
        include: "*"

