spring:
  application:
    name: accounts
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: ''
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
  profiles:
    active: default
  config:
    import: optional:configserver:http://localhost:8071
  rabbitmq:
    host: "localhost"
    port: 5672
    username: guest
    password: guest

server:
  port: 9090

management:
  endpoints:
    web:
      exposure:
        include: "*"

